@baseUrl = http://localhost:5000
##################################################


################################################## dbtest
GET {{baseUrl}}/dbtest/HangmanDB
#####

################################################## words
GET {{baseUrl}}/words
#####
