/*
 * HangmanBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// WordDTO
    /// </summary>
    [DataContract(Name = "WordDTO")]
    public partial class WordDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WordDTO" /> class.
        /// </summary>
        /// <param name="wort">wort.</param>
        /// <param name="schwierigkeit">schwierigkeit.</param>
        /// <param name="beschreibung">beschreibung.</param>
        public WordDTO(string wort = default, string schwierigkeit = default, string beschreibung = default)
        {
            this.Wort = wort;
            this.Schwierigkeit = schwierigkeit;
            this.Beschreibung = beschreibung;
        }

        /// <summary>
        /// Gets or Sets Wort
        /// </summary>
        [DataMember(Name = "wort", EmitDefaultValue = true)]
        public string Wort { get; set; }

        /// <summary>
        /// Gets or Sets Schwierigkeit
        /// </summary>
        [DataMember(Name = "schwierigkeit", EmitDefaultValue = true)]
        public string Schwierigkeit { get; set; }

        /// <summary>
        /// Gets or Sets Beschreibung
        /// </summary>
        [DataMember(Name = "beschreibung", EmitDefaultValue = true)]
        public string Beschreibung { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WordDTO {\n");
            sb.Append("  Wort: ").Append(Wort).Append("\n");
            sb.Append("  Schwierigkeit: ").Append(Schwierigkeit).Append("\n");
            sb.Append("  Beschreibung: ").Append(Beschreibung).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
