/*
 * HangmanBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OkMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OkMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OkMessage
        //private OkMessage instance;

        public OkMessageTests()
        {
            // TODO uncomment below to create an instance of OkMessage
            //instance = new OkMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OkMessage
        /// </summary>
        [Fact]
        public void OkMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" OkMessage
            //Assert.IsType<OkMessage>(instance);
        }

        /// <summary>
        /// Test the property 'IsOk'
        /// </summary>
        [Fact]
        public void IsOkTest()
        {
            // TODO unit test for the property 'IsOk'
        }

        /// <summary>
        /// Test the property 'Nr'
        /// </summary>
        [Fact]
        public void NrTest()
        {
            // TODO unit test for the property 'Nr'
        }
    }
}
