/*
 * HangmanBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WordDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WordDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WordDTO
        //private WordDTO instance;

        public WordDTOTests()
        {
            // TODO uncomment below to create an instance of WordDTO
            //instance = new WordDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WordDTO
        /// </summary>
        [Fact]
        public void WordDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" WordDTO
            //Assert.IsType<WordDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Wort'
        /// </summary>
        [Fact]
        public void WortTest()
        {
            // TODO unit test for the property 'Wort'
        }

        /// <summary>
        /// Test the property 'Schwierigkeit'
        /// </summary>
        [Fact]
        public void SchwierigkeitTest()
        {
            // TODO unit test for the property 'Schwierigkeit'
        }

        /// <summary>
        /// Test the property 'Beschreibung'
        /// </summary>
        [Fact]
        public void BeschreibungTest()
        {
            // TODO unit test for the property 'Beschreibung'
        }
    }
}
