/*
 * HangmanBackend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing HangmanBackendApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HangmanBackendApiTests : IDisposable
    {
        private HangmanBackendApi instance;

        public HangmanBackendApiTests()
        {
            instance = new HangmanBackendApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HangmanBackendApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HangmanBackendApi
            //Assert.IsType<HangmanBackendApi>(instance);
        }

        /// <summary>
        /// Test DbtestHangmanDBGet
        /// </summary>
        [Fact]
        public void DbtestHangmanDBGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DbtestHangmanDBGet();
            //Assert.IsType<OkMessage>(response);
        }

        /// <summary>
        /// Test WordsGet
        /// </summary>
        [Fact]
        public void WordsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WordsGet();
            //Assert.IsType<List<WordDTO>>(response);
        }
    }
}
